
name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a oneline script
        run: echo Hello, world!
  test:
    runs-on: ubuntu-latest
    
    steps:
      - run: [build]

